name: Compile ESP32

on:
  push:
    branches:
      - main
    paths:
      - '**/*.ino'
      - '**/*.cpp'
      - '**/*.h'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile sketch
        uses: wokwi/compile-sketch@v1
        with:
          sketch-path: . 

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: build/*.bin
