name: Build and Package ESP32 Firmware + SPIFFS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install arduino-cli
      run: |
        mkdir -p ~/.local/bin
        curl -fsSL https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz | tar -xzf - -C ~/.local/bin
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        chmod +x ~/.local/bin/arduino-cli

    - name: Install ESP32 Board
      run: |
        arduino-cli config init
        arduino-cli config add board_manager.additional_urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
        arduino-cli core update-index
        arduino-cli core install esp32:esp32

    - name: Compile Firmware
      run: |
        arduino-cli compile --fqbn esp32:esp32:esp32 CassiesArcade.ino --output-dir ./build

    - name: Generate SPIFFS
      run: |
        pip install mkspiffs
        mkdir -p spiffs
        cp index.html spiffs/
        mkspiffs -c spiffs -b 4096 -p 256 -s 0x500000 build/spiffs.bin

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: esp32-binaries
        path: |
          build/*.bin
