name: Build ESP32 Firmware and SPIFFS

on:
  push:
    paths:
      - '**.ino'
      - 'data/**'
      - '**.html'
      - '**.csv'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python and install esptool
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install esptool
        run: |
          pip install esptool

      - name: Install Arduino CLI and ESP32 core
        run: |
          curl -fsSL https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz -o arduino-cli.tar.gz
          tar -xzf arduino-cli.tar.gz
          sudo mv arduino-cli /usr/local/bin/
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli core update-index
          arduino-cli core install esp32:esp32@2.0.14

      - name: Compile firmware
        run: |
          mkdir -p build
          arduino-cli compile \
            --fqbn esp32:esp32:esp32 \
            CassiesArcade.ino \
            --output-dir ./build

      - name: List repo files
        run: |
          ls -la

      - name: List data folder contents
        run: |
          ls -la data

      - name: Build SPIFFS with mkspiffs
        run: |
          mkdir -p build
          curl -LO https://github.com/igrr/mkspiffs/releases/download/0.2.3/mkspiffs-0.2.3-arduino-esp32-linux64.tar.gz
          tar -xzf mkspiffs-0.2.3-arduino-esp32-linux64.tar.gz
          chmod +x mkspiffs-0.2.3-arduino-esp32-linux64/mkspiffs
          ./mkspiffs-0.2.3-arduino-esp32-linux64/mkspiffs -c data -b 4096 -p 256 -s 0x170000 build/spiffs.bin

      - name: Upload firmware binaries
        uses: actions/upload-artifact@v4
        with:
          name: firmware-binaries
          path: build/*.bin
