name: Build and Export ESP32 Firmware with SPIFFS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Arduino CLI
        run: |
          mkdir -p bin
          curl -fsSL https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz | tar -xz -C bin
          echo "$(pwd)/bin" >> $GITHUB_PATH

      - name: Install Platform & Libraries
        run: |
          arduino-cli config init
          arduino-cli core update-index
          arduino-cli core install esp32:esp32
          arduino-cli lib install FS SPIFFS WiFi WebServer

      - name: Compile Firmware
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32 \
            --build-property build.partitions=partitions.csv \
            --output-dir build .

      - name: Prepare SPIFFS
        run: |
          pip install mkspiffs
          mkdir -p build/spiffs
          cp -r data/* build/spiffs/
          mkspiffs -c build/spiffs -b 4096 -p 256 -s 0x170000 build/spiffs.bin

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ESP32_Binaries
          path: |
            build/*.bin
            build/spiffs.bin
