name: Build and Upload SPIFFS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-spiffs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y g++ git make

      - name: Build mkspiffs from Source
        run: |
          git clone --recursive https://github.com/igrr/mkspiffs.git
          cd mkspiffs
          make
          sudo cp mkspiffs /usr/local/bin/

      - name: Prepare SPIFFS Folder
        run: |
          mkdir -p spiffs
          cp index.html spiffs/

      - name: Build SPIFFS Binary
        run: |
          mkspiffs -c spiffs -b 4096 -p 256 -s 0x290000 build/spiffs.bin

      - name: Upload SPIFFS Binary
        uses: actions/upload-artifact@v4
        with:
          name: spiffs
          path: build/spiffs.bin
