name: Build ESP32 Firmware and SPIFFS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout Repository
      uses: actions/checkout@v3

    - name: 📦 Install Arduino CLI
      run: |
        mkdir -p ./bin
        curl -fsSL https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz | tar -xz -C ./bin
        ./bin/arduino-cli config init

    - name: 📥 Install ESP32 Board Platform
      run: |
        ./bin/arduino-cli core update-index
        ./bin/arduino-cli core install esp32:esp32

    - name: 🔧 Compile Firmware
      run: |
        ./bin/arduino-cli compile --fqbn esp32:esp32:esp32 CassiesArcade.ino

    - name: 📂 Create data folder for SPIFFS
      run: |
        mkdir -p data
        cp -r ./data/* ./data/ 2>/dev/null || true

    - name: 📦 Install Python SPIFFS Tool
      run: |
        pip install mkspiffs

    - name: 🧱 Build SPIFFS
      run: |
        mkspiffs -c ./data -b 4096 -p 256 -s 0x190000 spiffs.bin

    - name: 💾 Upload Binaries
      uses: actions/upload-artifact@v3
      with:
        name: esp32-binaries
        path: |
          CassiesArcade.ino.bin
          CassiesArcade.ino.partitions.bin
          CassiesArcade.ino.bootloader.bin
          spiffs.bin
