name: Compile ESP32

on:
  push:
    branches: [main]
    paths:
      - '**/*.ino'
      - '**/*.cpp'
      - '**/*.h'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Arduino CLI manually
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          sudo mv ./bin/arduino-cli /usr/local/bin/
          arduino-cli config init
          arduino-cli core update-index

      - name: Install ESP32 platform
        run: |
          arduino-cli core install esp32:esp32

      - name: Compile sketch
        run: |
          mkdir -p firmware
          arduino-cli compile --fqbn esp32:esp32:esp32 --output-dir ./firmware CassiesArcade.ino

      - name: Upload firmware binary
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: ./firmware/*.bin
