name: Build ESP32 Firmware + SPIFFS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip git make g++ wget

    - name: Set up Arduino CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        echo "$HOME/.arduino15/bin" >> $GITHUB_PATH
        arduino-cli core update-index
        arduino-cli core install esp32:esp32

    - name: Compile Firmware
      run: |
        arduino-cli compile \
          --fqbn esp32:esp32:esp32 \
          --output-dir build \
          CassiesArcade.ino

    - name: Upload Firmware Binaries
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: |
          build/*.bin

    - name: Clone mkspiffs
      run: |
        git clone --recursive https://github.com/igrr/mkspiffs.git
        cd mkspiffs && make
        sudo cp mkspiffs/mkspiffs /usr/local/bin/

    - name: Build SPIFFS Binary
      run: |
        echo "📁 Contents of /data:"
        ls -lh data
        mkspiffs -c data -b 4096 -p 256 -s 0x170000 spiffs.bin

    - name: Upload SPIFFS Binary
      uses: actions/upload-artifact@v4
      with:
        name: spiffs
        path: spiffs.bin
