name: Compile ESP32

on:
  push:
    paths:
      - '**.ino'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile sketch
        uses: wokwi/compile-sketch@v1
        with:
          sketch-path: .
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: build/*.bin
